const DATA = [
	{
		id: 0,
		busName : "HOGS A",
		model : "Suzuki76254",
		image : "https://media.istockphoto.com/photos/classical-red-bus-picture-id492620954?k=20&m=492620954&s=612x612&w=0&h=Cst9xheZ3R_Q9HOVysGWCo2foLnpIBMxSe4U1S6OyqE=",
		desc : "A comfortable and relaxing air-conditioned bus.",
		busLiner : "Dumbledore Lines",
		rating : 5,
        price : 80,
        tripsDates: "2022-08-05",
        source : "Makati",
        destination : "Manila",
        stops: "Mindoro",
        seatsAvail : 15,

	},
	{
		id: 1,
		busName : "LOCOMOTOR",
		model : "Hyundai3500",
		image : "https://thumbs.dreamstime.com/z/tour-bus-gray-sightseeing-charter-parked-urban-setting-80448029.jpg",
		desc : "A very classy suburban bus that has a top of the line motor.",
		busLiner : "Hermione Lines",
		rating : 5,
        price : 150,
        tripsDates: "2022-08-05",
        source : "Malabon",
        destination : "Makati",
        stops: "bacolod",
        seatsAvail : 18,

	},
	{
		id: 2,
		busName : "INGENITY",
		model : "Toyota4Z300",
		image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqkdpl0wLdIO6fhA4r_rba6n7Yqh-E-gUL9Q&usqp=CAU",
		desc : "A suburban convenient, efficient bus.",
		busLiner : "Dobby Lines",
		rating : 5,
        price : 120,
        tripsDates : "2022-08-01",
        source : "Makati",
        destination : "Baguio",
        stops: "Iloilo",
        seatsAvail : 14,

	},
	{
		id: 3,
		busName : "ZAPP 2022",
		model : "Mitsubishi2000",
		image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRdsmhICjoyBBoqp9DtkfQy70DD_-39nZMWQ&usqp=CAU",
		desc : "A fast and air-conditioned bus ready to take you anywhere.",
		busLiner : "Hermione Lines",
		rating : 5,
        price : 90,
        tripsDates : "2022-08-01",
        source : "Cebu",
        destination : "Batangas",
        stops: "Bicol",
        seatsAvail : 16,

	},
	{
		id: 4,
		busName : "ZENAIDE",
		model : "Mitsubishi3100",
		image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoUC4GjdZbvaa97zG8OOFz95KsLm1cRNQD9Q&usqp=CAU",
		desc : "A comfortable, luxurious lifestyle bus.",
		busLiner : "Dumbledore Lines",
		rating : 5,
        price : 100,
        tripsDates : "2022-08-01",
        source : "Bicol",
        destination : "Rizal",
        stops: "Bohol",
        seatsAvail : 18,

	},
	{
		id: 5,
		busName : "GAMMEL",
		model : "Toyota2022",
		image : "https://c8.alamy.com/comp/EDBE4G/vip-bus-luxury-bus-black-and-gold-illustration-EDBE4G.jpg",
		desc : "A super cozy bus",
		busLiner : "Hermione Lines",
		rating : 5,
        price : 70,
        tripsDates : "2022-08-01",
        source : "Rizal",
        destination : "Quezon city",
        stops: "Bicol",
        seatsAvail : 15,

	},
	{
		id: 6,
		busName : "SAMSAN",
		model : "Nissan7350",
		image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyLdAHyWoe-8HNwk99QwmRtWz2XxdIsjbjHg&usqp=CAU",
		desc : "A nice suburban bus that has miles on it.",
		busLiner : "Dumbledore Lines",
		rating : 5,
        price : 130,
        tripsDates : "2022-08-01",
        source : "Quezon city",
        destination : "Pasay",
        stops: "Cebu",
        seatsAvail : 16,

	},
	{
		id: 7,
		busName : "ZOHO",
		model : "Nissan Ultra",
		image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0gFDBSmYtg316BZYHo_1jj6Z7BvaBfyNYUw&usqp=CAU",
		desc : "A fast bus.",
		busLiner : "Dobby Lines",
		rating : 5,
        price : 120,
        tripsDates : "2022-08-01",
        source : "Pasay",
        destination : "Laoag",
        stops: "Manila",
        seatsAvail : 14,

	},
	{
		id: 8,
		busName : "ZANE",
		model : "Mitsubishi300",
		image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtYFMQl508cD2OROWOBhBk2XMYjL9_8MqbDQ&usqp=CAU",
		desc : "A cozy, ligth, breezy bus.",
		busLiner : "Dobby Lines",
		rating : 5,
        price : 110,
        tripsDates : "2022-08-01",
        source : "Laoag",
        destination : "Malabon",
        stops: "Cebu",
        seatsAvail : 20,

	},
	{
		id: 9,
		busName : "ZUMBA",
		model : "Toyota1200",
		image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSH5Z43IjFPOwfPHyOUj0SrbLAojSUILnZ_g&usqp=CAU",
		desc : "A bus that values feminism.",
		busLiner : "Hermione Lines",
		rating : 5,
        price : 100,
        tripsDates : "2022-08-01",
        source : "Naga",
        destination : "Marikina",
        stops: "Batangas",
        seatsAvail : 12,

	},
	{
		id: 10,
		busName : "AIRZ",
		model : "ToyotaSan",
		image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRftsSoKMGQeM_-oqAtMPNMyM_mrFFulNPIqw&usqp=CAU",
		desc : "A great public utility bus.",
		busLiner : "Hermione Lines",
		rating : 5,
        price : 80,
        tripsDates : "2022-08-01",
        source : "Cavite",
        destination : "Ilocos",
        stops: "Manila",
        seatsAvail : 15,

	},
	{
		id: 11,
		busName : "ZULU",
		model : "Mitsubishi Freelancer",
		image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmPNzHyIJa6amCc1-BLH8WzuVD6Kt2GuWyXQ&usqp=CAU",
		desc : "A super fast bus.",
		busLiner : "Dumbledore Lines",
		rating : 5,
        price : 90,
        tripsDates : "2022-08-01",
        source : "Ilocos",
        destination : "Cavite",
        stops: "Mindoro",
        seatsAvail : 17,
		
	},

]

export default DATA;